project:
  type: website
  output-dir: docs
website:
  title: "OVERVIEW AND UMBRELLA REVIEWS"
  site-url: "https://bougioukas.github.io/overviews/"
  favicon: "img/logo.png"
  reader-mode: true
  navbar:
    right:
      - text: Overview of reviews
        menu:
          - text: Methodology
            href: projects.qmd
          - text: Database
            href: projects.qmd
          - text: Reporting guidelines
            href: projects.qmd            
      - text: Umbrella review
        menu:
          - text: Methodology
            href: projects.qmd
          - text: Database
            href: projects.qmd
          - text: Reporting guidelines
            href: projects.qmd                 
    pinned: true
    logo: "img/logo.png"
    tools:
      - icon: github
        href: https://github.com/bougioukas/overviews
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)^®^"
    left: "&copy; Copyright 2024, Konstantinos I. Bougioukas. License: [Creative Commons Attribution-NonCommercial-NoDerivs 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/)."
  back-to-top-navigation: true
format:
  html:
    smooth-scroll: true
    theme: 
      - custom.scss
    grid:
      sidebar-width: 250px
      body-width: 950px
      margin-width: 300px
      gutter-width: 1.5em
    fontsize: 1.10em
    linestretch: 1.35      
    link-external-newwindow: true
    toc: true
    toc-location: right
    citations-hover: true
    footnotes-hover: true
    code-link: true
filters:
  - line-highlight
editor: source

